const LOCATIONS_DATA = [
  {
    "id": "granbury_opera_house",
    "title": "Historic Granbury Opera House Staircase",
    "category": "Theater & Performing Arts",
    "vibe": "Dreamy",
    "outfit": "Formal",
    "props": "Grand Staircase",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Dramatic pose in red gown on 1886 twin limestone curved staircases under vintage chandeliers inside Granbury Opera House.",
    "originalLocation": "Historic Granbury Opera House, Granbury, TX (Hood County)",
    "originalCaption": "⭐ Premier local theater venue in Hood County! Home to Granbury Theatre Company on Historic Granbury Square.",
    "imageLocalPath": "images/locations/granbury_opera_house.png",
    "googleMapsQuery": "Granbury Opera House Granbury TX"
  },
  {
    "id": "chandor_gardens_weatherford",
    "title": "Chandor Gardens Waterfall & Stone Bridge",
    "category": "Nature & Outdoors",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Stone Bridge",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Standing on Asian stone arch bridge framed by lush green foliage, waterfalls, and Chinese dragon masonry.",
    "originalLocation": "Chandor Gardens, Weatherford, TX (Parker County)",
    "originalCaption": "⭐ 3.5-acre estate mixing Chinese architecture and English formal gardens. Highly requested Weatherford location!",
    "imageLocalPath": "images/locations/chandor_gardens_weatherford.png",
    "googleMapsQuery": "Chandor Gardens Weatherford TX"
  },
  {
    "id": "weatherford_courthouse_beetle",
    "title": "Yellow Beetle at Weatherford Courthouse Square",
    "category": "Vintage Vehicles",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Yellow VW Beetle",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Leaning on yellow vintage Volkswagen Beetle hood parked along brick streets of 1886 Parker County Courthouse.",
    "originalLocation": "Historic Weatherford Town Square, Weatherford, TX (Parker County)",
    "originalCaption": "⭐ High-contrast pop color pairing yellow VW bug with 1886 French Second Empire limestone courthouse.",
    "imageLocalPath": "images/locations/weatherford_courthouse_beetle.png",
    "googleMapsQuery": "Parker County Courthouse Weatherford TX"
  },
  {
    "id": "aledo_field_beetle",
    "title": "Yellow Beetle Sunset Prairie",
    "category": "Vintage Vehicles",
    "vibe": "Dreamy",
    "outfit": "Casual",
    "props": "Yellow VW Beetle",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Sitting on yellow VW Beetle hood in open golden prairie field during warm Texas sunset.",
    "originalLocation": "Aledo Prairie Fields & Countryside, Aledo, TX (Parker County)",
    "originalCaption": "⭐ Iconic open Texas sky and rolling hills in Aledo / Willow Park countryside.",
    "imageLocalPath": "images/locations/aledo_field_beetle.png",
    "googleMapsQuery": "Aledo Texas countryside field"
  },
  {
    "id": "granbury_lake_sunset",
    "title": "Lake Granbury Waterfront & Boat Docks",
    "category": "Nature & Outdoors",
    "vibe": "Playful",
    "outfit": "Dress",
    "props": "Waterfront Dock",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Barefoot sitting on edge of wooden boat dock at Lake Granbury Beach Park kicking water droplets at golden hour.",
    "originalLocation": "Lake Granbury City Beach & Waterfront, Granbury, TX (Hood County)",
    "originalCaption": "⭐ Popular Hood County waterfront location for sunset dock and beach shore portraits.",
    "imageLocalPath": "images/locations/granbury_lake_sunset.png",
    "googleMapsQuery": "Lake Granbury City Beach Park Granbury TX"
  },
  {
    "id": "mineral_wells_mural",
    "title": "Greetings from Mineral Wells Postcard Mural",
    "category": "City & Urban",
    "vibe": "Moody",
    "outfit": "Casual",
    "props": "Mural Wall",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Walking stride past vibrant hand-painted retro postcard mural wall with shadow contrast.",
    "originalLocation": "Downtown Mineral Wells Mural District, Mineral Wells, TX (Parker / Palo Pinto area)",
    "originalCaption": "⭐ High-contrast artistic street art backdrop near historic Baker Hotel plaza.",
    "imageLocalPath": "images/locations/mineral_wells_mural.png",
    "googleMapsQuery": "Greetings from Mineral Wells mural"
  },
  {
    "id": "acton_prairie_farmhouse",
    "title": "Acton Nature Center Historic Farmhouse",
    "category": "Nature & Outdoors",
    "vibe": "Classic",
    "outfit": "Casual",
    "props": "Western Boots",
    "gender": "female",
    "isLocalSpot": true,
    "poseDescription": "Seated on porch step of 1930s white wood farmhouse in prairie grass holding cowboy hat.",
    "originalLocation": "Acton Nature Center, Granbury / Acton, TX (Hood County)",
    "originalCaption": "⭐ Historic 1930s homestead surrounded by native Texas wildflowers and oak trees.",
    "imageLocalPath": "images/locations/acton_prairie_farmhouse.png",
    "googleMapsQuery": "Acton Nature Center Granbury TX"
  },
  {
    "id": "theater_stage_dress",
    "title": "Center Stage Spotlight & Emerald Dress",
    "category": "Theater & Performing Arts",
    "vibe": "Dreamy",
    "outfit": "Formal",
    "props": "Stage Spotlight",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Standing dramatic posture under warm stage spotlight on historic auditorium stage with soft atmospheric haze.",
    "originalLocation": "Historic Performing Arts Playhouse Stage",
    "originalCaption": "Creative editorial stage setup highlighting passion for drama, musical theater, and performing arts.",
    "imageLocalPath": "images/locations/theater_stage_dress.png",
    "googleMapsQuery": "local performing arts theater playhouse"
  },
  {
    "id": "theater_auditorium_seats",
    "title": "Plush Red Velvet Auditorium Rows",
    "category": "Theater & Performing Arts",
    "vibe": "Playful",
    "outfit": "Casual",
    "props": "Drama Script",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Seated casually in middle row of red velvet theater seats holding and reading highlighted drama script.",
    "originalLocation": "High School Auditorium & Community Playhouse",
    "originalCaption": "Showcasing drama passion surrounded by classic theater seating and soft ambient light.",
    "imageLocalPath": "images/locations/theater_auditorium_seats.png",
    "googleMapsQuery": "community theater auditorium"
  },
  {
    "id": "theater_marquee_lights",
    "title": "Glowing Vintage Marquee & Night Lights",
    "category": "Theater & Performing Arts",
    "vibe": "Moody",
    "outfit": "Casual",
    "props": "Marquee Sign",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Nighttime portrait under glowing lightbulbs of vintage movie/playhouse marquee sign.",
    "originalLocation": "Downtown Historic Theater District",
    "originalCaption": "Cinematic night portrait taking advantage of marquee bulbs and city reflections.",
    "imageLocalPath": "images/locations/theater_marquee_lights.png",
    "googleMapsQuery": "vintage theater marquee downtown"
  },
  {
    "id": "yellow_beetle_brick",
    "title": "Yellow Vintage Beetle & Brick Alley",
    "category": "Vintage Vehicles",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Yellow VW Beetle",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Leaning back against yellow classic 1970s Volkswagen Beetle hood in front of dark rustic brick wall.",
    "originalLocation": "Downtown Historic Alleyway",
    "originalCaption": "High-contrast editorial color pop pairing bright yellow beetle against textured urban brick.",
    "imageLocalPath": "images/locations/yellow_beetle_brick.png",
    "googleMapsQuery": "downtown brick alleyway"
  },
  {
    "id": "yellow_beetle_field",
    "title": "Yellow Beetle Road Trip Meadow Sunset",
    "category": "Vintage Vehicles",
    "vibe": "Dreamy",
    "outfit": "Casual",
    "props": "Yellow VW Beetle",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Sitting casually on open driver window frame during golden hour sunset in wildflower meadow.",
    "originalLocation": "Open Country Meadow Roadway",
    "originalCaption": "Whimsical summer road-trip vibe with vintage yellow bug and golden sunset light.",
    "imageLocalPath": "images/locations/yellow_beetle_field.png",
    "googleMapsQuery": "country road meadow scenic outlook"
  },
  {
    "id": "yellow_beetle_steering",
    "title": "Windshield Framing & Steering Wheel Candid",
    "category": "Vintage Vehicles",
    "vibe": "Playful",
    "outfit": "Casual",
    "props": "Steering Wheel",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Natural laughing candid framed through windshield at steering wheel with sun flare on glass.",
    "originalLocation": "Vintage Beetle Driver Seat",
    "originalCaption": "Authentic close-up framing capturing personality behind the wheel of her prized yellow bug.",
    "imageLocalPath": "images/locations/yellow_beetle_steering.png",
    "googleMapsQuery": "scenic drive parking area"
  },
  {
    "id": "golf_course",
    "title": "Golf Course & Manicured Greens (Alex)",
    "category": "Hobbies & Interests",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Golf Clubs",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Casual seated or standing pose with golf club on open manicured greens during golden hour.",
    "originalLocation": "Bluegrass Yacht & Country Club, Hendersonville, TN",
    "originalCaption": "Alex plays golf for his school, so including golf in his senior session was another number one request.",
    "imageLocalPath": "images/locations/senior_boy_golf_course_location.jpg",
    "googleMapsQuery": "local golf course"
  },
  {
    "id": "library",
    "title": "Quiet Library & Bookshelf Aisle (Raygan)",
    "category": "Hobbies & Interests",
    "vibe": "Playful",
    "outfit": "Casual",
    "props": "Books",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Seated on floor between bookshelves holding favorite books, natural soft window light.",
    "originalLocation": "Gallatin Public Library, Gallatin, TN",
    "originalCaption": "Find a bright spot in your local library for a high school senior who loves reading.",
    "imageLocalPath": "images/locations/senior_girl_library-scaled.jpg",
    "googleMapsQuery": "public library bookstore"
  },
  {
    "id": "vintage_car",
    "title": "Antique Vintage Car Fender & Hood (Raygan)",
    "category": "Vintage Vehicles",
    "vibe": "Playful",
    "outfit": "Casual",
    "props": "Antique Vehicle",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Casual leaning or sitting on classic antique car hood/fender with boots and jeans.",
    "originalLocation": "Private Residence Antique Car Collection",
    "originalCaption": "Raygan loves vintage cars, so she asked her neighbor if she could come to their house to take some photos in front of their antique cars.",
    "imageLocalPath": "images/locations/senior_vintage_car.jpg",
    "googleMapsQuery": "vintage car classic auto"
  },
  {
    "id": "arcade",
    "title": "Retro Pinball & Arcade Cabinets (Ellie)",
    "category": "Hobbies & Interests",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Arcade Cabinets",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Interactive candid pose holding joystick/buttons with glowing cabinet RGB light.",
    "originalLocation": "16-Bit Bar + Arcade, Downtown Nashville, TN",
    "originalCaption": "Ellie chose a local arcade for her senior session. This is a restaurant and bar with arcade games located in downtown Nashville.",
    "imageLocalPath": "images/locations/senior_arcade.jpg",
    "googleMapsQuery": "arcade entertainment center"
  },
  {
    "id": "sunset_field",
    "title": "Golden Hour Grass & Sunset Hills (Emma)",
    "category": "Nature & Outdoors",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Tall Grass",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Standing twirl or walking pose in knee-deep golden field grass with warm backlight.",
    "originalLocation": "Rolling Hill Field near Studio, Hendersonville, TN",
    "originalCaption": "17 year old Emma looked stunning in this white dress and gorgeous field. The tall grass, rolling hills, and pink sunset made a dreamy backdrop.",
    "imageLocalPath": "images/locations/senior_girl_sunset_field-1.jpg",
    "googleMapsQuery": "nature park open field"
  },
  {
    "id": "lake_boy",
    "title": "Lakeside Shore & Sunset Water View (Alex)",
    "category": "Nature & Outdoors",
    "vibe": "Classic",
    "outfit": "Casual",
    "props": "Waterfront",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Casual sitting on waterfront rocks looking over water at sunset.",
    "originalLocation": "Old Hickory Lake, Hendersonville, TN",
    "originalCaption": "Alex spends a lot of time on the lake from fishing to boating, so the lake was one of his most requested locations.",
    "imageLocalPath": "images/locations/senior_boy_lake_location.jpg",
    "googleMapsQuery": "lake shoreline waterfront park"
  },
  {
    "id": "lake_girl",
    "title": "Serene Lake Shoreline Sunset (Alyssa)",
    "category": "Nature & Outdoors",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Water",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Barefoot standing by water edge looking back over shoulder during sunset reflections.",
    "originalLocation": "Lakeside Park, Hendersonville, TN",
    "originalCaption": "Alyssa chose to finish her senior portrait session by the lake at sunset.",
    "imageLocalPath": "images/locations/senior_girl_lake_location.jpg",
    "googleMapsQuery": "lake beach shoreline"
  },
  {
    "id": "barn_white_dress",
    "title": "Rustic Wood Barn & Hay Bales (Ayden)",
    "category": "Nature & Outdoors",
    "vibe": "Classic",
    "outfit": "Dress",
    "props": "Cowboy Boots",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Standing framed by weathered barn doors in white sundress and cowboy boots.",
    "originalLocation": "Historic Farm Barn, Middle Tennessee",
    "originalCaption": "As soon as Ayden showed me her white dress and cowboy boots, I knew we had to go country! She wore this outfit at the barn and at a field with hay bales.",
    "imageLocalPath": "images/locations/senior_girl_barn-scaled.jpg",
    "googleMapsQuery": "rustic barn farm"
  },
  {
    "id": "red_barn",
    "title": "Classic Red Barn Wood Texture (Abigail)",
    "category": "Nature & Outdoors",
    "vibe": "Classic",
    "outfit": "Casual",
    "props": "Wood Texture",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Leaning back against weathered red painted wood planks with warm directional light.",
    "originalLocation": "Red Barn behind Studio, Hendersonville, TN",
    "originalCaption": "Abigail had so much variety in her locations. This red barn located behind my former studio added the perfect rustic touch.",
    "imageLocalPath": "images/locations/senior_barn_location.jpg",
    "googleMapsQuery": "historic farm red barn"
  },
  {
    "id": "wildflowers",
    "title": "Blooming Wildflower Field (Liza)",
    "category": "Nature & Outdoors",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Flowers",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Gentle crouch or walk among tall colorful flower stems with soft natural bokeh.",
    "originalLocation": "Flower Farm, Summer Bloom, Hendersonville area, TN",
    "originalCaption": "Liza wanted bold colors and pretty flowers for her senior photos. We found a flower farm about 30 minutes from my studio.",
    "imageLocalPath": "images/locations/senior_wildflowers.jpg",
    "googleMapsQuery": "flower farm botantical garden"
  },
  {
    "id": "sunflowers",
    "title": "Late Summer Sunflower Patch (Liza)",
    "category": "Nature & Outdoors",
    "vibe": "Playful",
    "outfit": "Casual",
    "props": "Sunflowers",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Framed waist-up between massive golden sunflower blooms with bright joyful smile.",
    "originalLocation": "Sunflower Patch Farm, Middle TN",
    "originalCaption": "Sunflowers bloom in the late summer. We found this sunflower farm for Liza's senior shoot.",
    "imageLocalPath": "images/locations/senior_sunflowers.jpg",
    "googleMapsQuery": "sunflower field farm"
  },
  {
    "id": "beach_boy",
    "title": "Relaxed Coastal Beach Walk (Baylor)",
    "category": "Nature & Outdoors",
    "vibe": "Casual",
    "outfit": "Casual",
    "props": "Ocean Shoreline",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Casual hoodie and jeans walk on wet sand near surf shoreline.",
    "originalLocation": "Destin Beach Shoreline, FL",
    "originalCaption": "17 year old Baylor scheduled his senior photos for his fall break. His casual hoodie and confident attitude fit the relaxed vibe at the beach.",
    "imageLocalPath": "images/locations/senior_boy_beach.jpg",
    "googleMapsQuery": "public beach shoreline"
  },
  {
    "id": "beach_jetties",
    "title": "Coastal Rock Jetties & Dunes (Reagan)",
    "category": "Nature & Outdoors",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Rock Jetties",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Seated on sea wall / rock jetty rocks with ocean breeze and coastal sky.",
    "originalLocation": "Destin Jetties & Dunes, FL",
    "originalCaption": "High school senior Reagan loved the unique look of the jetties located at the beach.",
    "imageLocalPath": "images/locations/senior_girl_beach.jpg",
    "googleMapsQuery": "coastal jetty beach pier"
  },
  {
    "id": "beach_palm_trees",
    "title": "Palm Tree Path & FSU Polo (Briley Noles)",
    "category": "Nature & Outdoors",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Palm Trees",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Standing under lush palm fronds in university polo and baseball cap representing FSU.",
    "originalLocation": "Sidewalk near Destin Jetties, FL",
    "originalCaption": "This is my son, Briley. He chose to wear a polo shirt and hat to represent FSU. We found a great spot in Destin that gave the beach feel.",
    "imageLocalPath": "images/locations/brinolesfb.jpg",
    "googleMapsQuery": "palm tree walkway park"
  },
  {
    "id": "gallatin_square_urban",
    "title": "Historic Gallatin Town Square (Abigail)",
    "category": "City & Urban",
    "vibe": "Classic",
    "outfit": "Casual",
    "props": "Architectural Brick",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Walking across brick alleyway with vintage storefront windows behind.",
    "originalLocation": "Historic Gallatin Town Square, Gallatin, TN",
    "originalCaption": "Abigail had fun with different poses using the different backdrops in this urban area.",
    "imageLocalPath": "images/locations/senior_urban_location-scaled.jpg",
    "googleMapsQuery": "historic downtown town square"
  },
  {
    "id": "urban_door_wall",
    "title": "Rustic Urban Alley Doorway (Abigail)",
    "category": "City & Urban",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Painted Door",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Leaning shoulder against teal/grey painted industrial alley door in bold contrast outfit.",
    "originalLocation": "Downtown Alley, Middle TN",
    "originalCaption": "A location that may not look very pretty when you drive up can turn into a magical spot for photos. I love how the colors of her outfit pop.",
    "imageLocalPath": "images/locations/senior_industrial_location.jpg",
    "googleMapsQuery": "downtown brick alleyway"
  },
  {
    "id": "flower_truck",
    "title": "Amelia's Vintage Flower Truck (Bailey)",
    "category": "City & Urban",
    "vibe": "Dreamy",
    "outfit": "Dress",
    "props": "Flowers",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Leaning near bed of flower pop-up truck holding fresh bouquet in lace dress.",
    "originalLocation": "Amelia's Flower Truck Pop-Up, 12 South, Nashville",
    "originalCaption": "I knew the flowers at Amelia's Flower Truck and Bailey's lace dress would look so dreamy together.",
    "imageLocalPath": "images/locations/senior_amelias_flower_truck.jpg",
    "googleMapsQuery": "flower truck pop up garden market"
  },
  {
    "id": "12south_ivy_wall",
    "title": "12 South Stucco Wall & Climbing Ivy (Claire)",
    "category": "City & Urban",
    "vibe": "Classic",
    "outfit": "Dress",
    "props": "Ivy Greenery",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Full-length posture leaning against warm stucco wall draped in climbing ivy.",
    "originalLocation": "12 South Boutique Side Streets, Nashville, TN",
    "originalCaption": "Different urban neighborhoods give off their own vibes. This is Claire at one of my favorite senior photo spots in 12 South.",
    "imageLocalPath": "images/locations/senior_girl_urban_nashville_gulch.jpg",
    "googleMapsQuery": "ivy covered wall courtyard"
  },
  {
    "id": "12south_metal_stairs",
    "title": "12 South Industrial Fire Escape (Claire)",
    "category": "City & Urban",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Metal Staircase",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Seated on metal stair step looking down toward camera with leading line geometry.",
    "originalLocation": "12 South Alley Staircase, Nashville, TN",
    "originalCaption": "This is another quiet spot that we found off of a side street in 12 South with metal stairs.",
    "imageLocalPath": "images/locations/urban_senior_girl_metal_stairs.jpg",
    "googleMapsQuery": "fire escape staircase alley"
  },
  {
    "id": "gulch_urban_city",
    "title": "The Gulch Urban City Street",
    "category": "City & Urban",
    "vibe": "Classic",
    "outfit": "Casual",
    "props": "Modern Storefront",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Candid walking stride along clean modern city sidewalk with blurred background buildings.",
    "originalLocation": "The Gulch Neighborhood, Nashville, TN",
    "originalCaption": "The Gulch is a walkable neighborhood just a few blocks from Broadway. This area gives your senior photos an elevated urban feel.",
    "imageLocalPath": "images/locations/senior_girl_urban_city.jpg",
    "googleMapsQuery": "downtown boutique shopping street"
  },
  {
    "id": "printers_alley",
    "title": "Printer's Alley Neon & Twinkle Lights (Bailey)",
    "category": "City & Urban",
    "vibe": "Moody",
    "outfit": "Formal",
    "props": "String Lights",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Spontaneous laugh/turn in cobblestone alley lit by overhead string bulbs and neon signs.",
    "originalLocation": "Printer's Alley, Downtown Nashville, TN",
    "originalCaption": "Bailey had so much fun in Printer's Alley. I love how the bright lights and her cheerful laugh give off that completely care free feeling.",
    "imageLocalPath": "images/locations/senior_girl_printers_alley.jpg",
    "googleMapsQuery": "historic alley string lights"
  },
  {
    "id": "mural_alley",
    "title": "Mural Alleyway & Shadow Lighting (Claire)",
    "category": "City & Urban",
    "vibe": "Moody",
    "outfit": "Casual",
    "props": "Wall Art",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Three-quarter pose in narrow alley with wall shadows and directional side light.",
    "originalLocation": "Downtown Mural Alleyway, Nashville, TN",
    "originalCaption": "Moody lighting a colorful murals added a touch of fun to Claire's senior session.",
    "imageLocalPath": "images/locations/urban_alley_senior_girl.jpg",
    "googleMapsQuery": "mural alley art district"
  },
  {
    "id": "graffiti_wall",
    "title": "Saturated Gulch Graffiti Wall (Sarah)",
    "category": "City & Urban",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Graffiti",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Crossed-arms confidence stance centered against bright saturated graffiti aerosol graphics.",
    "originalLocation": "Gulch Graffiti Wall, Nashville, TN",
    "originalCaption": "Sarah loved the bright colors in this graffiti wall that we found in the Gulch area of Nashville, TN.",
    "imageLocalPath": "images/locations/senior_graffiti_wall.jpg",
    "googleMapsQuery": "graffiti mural wall street art"
  },
  {
    "id": "rooftop_parking",
    "title": "Downtown Parking Garage Rooftop",
    "category": "Skyline & Views",
    "vibe": "Dreamy",
    "outfit": "Casual",
    "props": "Skyline View",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Sitting on perimeter ledge with open sky and city high-rises softly blurred behind.",
    "originalLocation": "Downtown Parking Garage Rooftop, Nashville, TN",
    "originalCaption": "Rooftop parking lots offer great skyline views of the city as well as that dreamy golden light from sunsets.",
    "imageLocalPath": "images/locations/senior_girl_rooftop_parking_lot.jpg",
    "googleMapsQuery": "downtown parking garage rooftop view"
  },
  {
    "id": "pedestrian_bridge",
    "title": "John Seigenthaler Pedestrian Bridge (Sarah)",
    "category": "Skyline & Views",
    "vibe": "Moody",
    "outfit": "Dress",
    "props": "Bridge Trusses",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Standing center between repeating steel arches at sunset looking back into camera.",
    "originalLocation": "Pedestrian Bridge, Nashville, TN",
    "originalCaption": "The Pedestrian Bridge is a great way to capture the Nashville skyline with modern lines.",
    "imageLocalPath": "images/locations/nashville_pedestrian_bridge_seniorshoot-scaled.jpg",
    "googleMapsQuery": "pedestrian bridge river view"
  },
  {
    "id": "capitol_building",
    "title": "Tennessee State Capitol Stone Columns (Ella)",
    "category": "Skyline & Views",
    "vibe": "Classic",
    "outfit": "Suit",
    "props": "Stone Pillars",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Professional stance between grand limestone pillars in tailored suit.",
    "originalLocation": "Tennessee State Capitol, Nashville, TN",
    "originalCaption": "The Capital Building in downtown Nashville made the perfect backdrop for Ella who is involved in SGA and wants to be a lawyer.",
    "imageLocalPath": "images/locations/senior_girl_capital_building-1-scaled.jpg",
    "googleMapsQuery": "state capitol government building columns"
  },
  {
    "id": "rocky_construction",
    "title": "Raw Rock Quarry & Gold Sequin Gown (Abigail)",
    "category": "Industrial & Textures",
    "vibe": "Edgy",
    "outfit": "Dress",
    "props": "Rock Texture",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "High-contrast dramatic pose sitting on angular rock mound wearing metallic gold sequin gown.",
    "originalLocation": "Industrial Quarry Lot, Hendersonville, TN",
    "originalCaption": "Here we see 17 year old Abigail posing in an industrial location. It shows off her gold dress perfectly!",
    "imageLocalPath": "images/locations/senior_outdoor_location.jpg",
    "googleMapsQuery": "quarry gravel lot industrial site"
  },
  {
    "id": "chain_link_fence_girl",
    "title": "Sunlit Chain Link Industrial Fence (Rachel)",
    "category": "Industrial & Textures",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Wire Fence",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Hands woven lightly into chain-link fence wire with glowing backlight bokeh.",
    "originalLocation": "Commercial Lot Fence, Hendersonville, TN",
    "originalCaption": "We found this industrial location as we were driving during Rachel's shoot. This outfit and industrial location looked great together.",
    "imageLocalPath": "images/locations/senior_girl_industrial_location.jpg",
    "googleMapsQuery": "industrial fence commercial lot"
  },
  {
    "id": "chain_link_fence_abigail",
    "title": "Pop-Color Top & Chain Link Fence (Abigail)",
    "category": "Industrial & Textures",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Wire Fence",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Abigail wearing pop-color top leaning against industrial wire fence.",
    "originalLocation": "Industrial Lot Fence, Middle TN",
    "originalCaption": "You can find chain link fences all over the place. Abigail's outfit adds a pop of color and fun.",
    "imageLocalPath": "images/locations/abigail_senior_SPP_21.jpg",
    "googleMapsQuery": "industrial fence site"
  },
  {
    "id": "metal_garage_door",
    "title": "Rust Orange Industrial Garage Door (Gavin)",
    "category": "Industrial & Textures",
    "vibe": "Edgy",
    "outfit": "Casual",
    "props": "Corrugated Metal",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Leaning back against ribbed rust-orange painted metal door with hands in pockets.",
    "originalLocation": "Abandoned Car Wash, Hendersonville, TN",
    "originalCaption": "I found this amazing rust orange garage door at an abandoned car wash near my studio in Hendersonville.",
    "imageLocalPath": "images/locations/senior_boy_urban-1.jpg",
    "googleMapsQuery": "abandoned garage corrugated metal door"
  },
  {
    "id": "high_school_bleachers",
    "title": "High School Stadium Bleachers (Hayden)",
    "category": "High School Campus",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Sports Gear",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Seated on aluminum bleacher bench with sports stick and team jacket.",
    "originalLocation": "Pope John Paul II High School, Hendersonville, TN",
    "originalCaption": "Hayden plays lacrosse for his high school, so we used their field and bleachers to incorporate lacrosse photos.",
    "imageLocalPath": "images/locations/senior_boy_high_school_bleachers.jpg",
    "googleMapsQuery": "high school stadium bleachers"
  },
  {
    "id": "high_school_track",
    "title": "Running Track Red Lanes (Gavin)",
    "category": "High School Campus",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Track Oval",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Runner crouch start stance on lane white line of red rubber track surface.",
    "originalLocation": "High School Track Oval, Middle TN",
    "originalCaption": "Gavin was offered a scholarship during his senior year to run track in college, so incorporating track into his senior session was most important.",
    "imageLocalPath": "images/locations/senior_boy_high_school_track-scaled.jpg",
    "googleMapsQuery": "high school running track field"
  },
  {
    "id": "football_field_lacrosse",
    "title": "Varsity Field Endzone & Turf (Hayden)",
    "category": "High School Campus",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Sports Equipment",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Standing holding helmet/stick on green field turf near goalpost.",
    "originalLocation": "Varsity Stadium Field, Hendersonville, TN",
    "originalCaption": "Hayden wanted to incorporate lacrosse in his high school senior session. We used the bleachers and football field.",
    "imageLocalPath": "images/locations/senior_football_field.jpg",
    "googleMapsQuery": "high school football athletic field"
  },
  {
    "id": "baseball_field",
    "title": "Dugout & Baseball Diamond (Houston)",
    "category": "High School Campus",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Bat / Glove",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Seated on dugout bench resting bat over shoulder looking toward home plate.",
    "originalLocation": "Beech High School Baseball Field, Shackle Island, TN",
    "originalCaption": "Houston loved playing baseball for Beech High School, so including his favorite sport in his senior photos was his number one request.",
    "imageLocalPath": "images/locations/senior_baseball_field.jpg",
    "googleMapsQuery": "baseball diamond dugout field"
  },
  {
    "id": "campus_letter_jacket",
    "title": "Campus Courtyard & Letter Jacket (Hayden)",
    "category": "High School Campus",
    "vibe": "Classic",
    "outfit": "Sports",
    "props": "Letter Jacket",
    "gender": "male",
    "isLocalSpot": false,
    "poseDescription": "Standing near high school archway wearing varsity letter jacket.",
    "originalLocation": "Pope John Paul II Campus Courtyard, Hendersonville, TN",
    "originalCaption": "Hayden chose to wear his letter jacket for his senior photos at his school.",
    "imageLocalPath": "images/locations/senior_boy_letter_jacket.jpg",
    "googleMapsQuery": "high school campus courtyard"
  },
  {
    "id": "studio_headshot",
    "title": "Clean Studio Headshot & Backdrop (Abigail)",
    "category": "Studio",
    "vibe": "Classic",
    "outfit": "Dress",
    "props": "Studio Stool",
    "gender": "female",
    "isLocalSpot": false,
    "poseDescription": "Timeless seated stool headshot on neutral grey backdrop with studio softbox lighting.",
    "originalLocation": "Shannon Payne Studio, Hendersonville, TN",
    "originalCaption": "This simple studio pose is a great example of a senior studio headshot. The clean background keeps the senior portrait classic.",
    "imageLocalPath": "images/locations/senior_studio-scaled.jpg",
    "googleMapsQuery": "portrait studio headshot rental"
  }
];
