const LOCATIONS_DATA = [
  {
    id: "golf_course",
    title: "Golf Course & Manicured Greens",
    category: "Hobbies & Interests",
    vibe: "Classic",
    outfit: "Sports",
    props: "Sports Equipment",
    gender: "male",
    poseDescription: "Casual seated or standing pose with golf club on open manicured greens during golden hour.",
    originalLocation: "Bluegrass Yacht & Country Club, Hendersonville, TN",
    originalCaption: "Alex plays golf for his school, so including golf in his senior session was a top request.",
    imageLocalPath: "images/locations/golf_course.jpg",
    googleMapsQuery: "local golf course"
  },
  {
    id: "library",
    title: "Quiet Library & Bookstore Aisle",
    category: "Hobbies & Interests",
    vibe: "Playful",
    outfit: "Casual",
    props: "Books",
    gender: "female",
    poseDescription: "Seated on floor between bookshelves holding favorite books, natural soft window light.",
    originalLocation: "Gallatin Public Library, Gallatin, TN",
    originalCaption: "Find a bright spot in your local library for a high school senior who loves reading.",
    imageLocalPath: "images/locations/library.jpg",
    googleMapsQuery: "public library bookstore"
  },
  {
    id: "vintage_car",
    title: "Vintage Car Hood & Pickup Bed",
    category: "Hobbies & Interests",
    vibe: "Playful",
    outfit: "Casual",
    props: "Vehicle",
    gender: "female",
    poseDescription: "Casual leaning or sitting on classic antique car hood/fender with boots and jeans.",
    originalLocation: "Private Residence Antique Car Collection",
    originalCaption: "Raygan loves vintage cars and asked her neighbor to take photos with their antique vehicle.",
    imageLocalPath: "images/locations/vintage_car.jpg",
    googleMapsQuery: "vintage car classic auto"
  },
  {
    id: "arcade",
    title: "Retro Arcade & Neon Lights",
    category: "Hobbies & Interests",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Arcade Cabinets",
    gender: "female",
    poseDescription: "Interactive candid pose holding joystick/buttons with glowing cabinet RGB light.",
    originalLocation: "16-Bit Bar + Arcade, Downtown Nashville, TN",
    originalCaption: "Ellie chose a local arcade with pinball and arcade games for brightly colored photos.",
    imageLocalPath: "images/locations/arcade.jpg",
    googleMapsQuery: "arcade entertainment center"
  },
  {
    id: "sunset_field",
    title: "Golden Grass Sunset Field",
    category: "Nature & Outdoors",
    vibe: "Dreamy",
    outfit: "Dress",
    props: "Tall Grass",
    gender: "female",
    poseDescription: "Standing twirl or walking pose in knee-deep golden field grass with warm backlight.",
    originalLocation: "Rolling Hill Field near Studio, Hendersonville, TN",
    originalCaption: "Emma in a white dress with tall grass, rolling hills, and a pink sunset backdrop.",
    imageLocalPath: "images/locations/sunset_field.jpg",
    googleMapsQuery: "nature park open field"
  },
  {
    id: "lake_boy",
    title: "Lakeside Shore & Rocks",
    category: "Nature & Outdoors",
    vibe: "Casual",
    outfit: "Casual",
    props: "Water",
    gender: "male",
    poseDescription: "Casual sitting on waterfront rocks looking over water at sunset.",
    originalLocation: "Old Hickory Lake, Hendersonville, TN",
    originalCaption: "Alex spends time on the lake fishing and boating, making water a key location.",
    imageLocalPath: "images/locations/lake_boy.jpg",
    googleMapsQuery: "lake shoreline waterfront park"
  },
  {
    id: "lake_girl",
    title: "Serene Lake Shoreline Sunset",
    category: "Nature & Outdoors",
    vibe: "Dreamy",
    outfit: "Dress",
    props: "Water",
    gender: "female",
    poseDescription: "Barefoot standing by water edge looking back over shoulder during sunset reflections.",
    originalLocation: "Lakeside Park, Hendersonville, TN",
    originalCaption: "Alyssa finished her session by the lake at sunset near Hendersonville.",
    imageLocalPath: "images/locations/lake_girl.jpg",
    googleMapsQuery: "lake beach shoreline"
  },
  {
    id: "barn_white_dress",
    title: "Rustic Wood Barn & Hay Bales",
    category: "Nature & Outdoors",
    vibe: "Classic",
    outfit: "Dress",
    props: "Cowboy Boots",
    gender: "female",
    poseDescription: "Standing framed by weathered barn doors in white sundress and cowboy boots.",
    originalLocation: "Historic Farm Barn, Middle Tennessee",
    originalCaption: "Ayden wore her white dress and cowboy boots at a rustic wood barn.",
    imageLocalPath: "images/locations/barn_white_dress.jpg",
    googleMapsQuery: "rustic barn farm"
  },
  {
    id: "red_barn",
    title: "Classic Red Barn Texture",
    category: "Nature & Outdoors",
    vibe: "Classic",
    outfit: "Casual",
    props: "Wood Texture",
    gender: "female",
    poseDescription: "Leaning back against weathered red painted wood planks with warm directional light.",
    originalLocation: "Red Barn behind Studio, Hendersonville, TN",
    originalCaption: "Abigail used a red barn location to add a rustic touch to her photos.",
    imageLocalPath: "images/locations/red_barn.jpg",
    googleMapsQuery: "historic farm red barn"
  },
  {
    id: "wildflowers",
    title: "Blooming Wildflower Meadow",
    category: "Nature & Outdoors",
    vibe: "Dreamy",
    outfit: "Dress",
    props: "Flowers",
    gender: "female",
    poseDescription: "Gentle crouch or walk among tall colorful flower stems with soft natural bokeh.",
    originalLocation: "Flower Farm, Summer Bloom, Hendersonville area, TN",
    originalCaption: "Liza wanted bold colors and pretty flowers from a local flower farm.",
    imageLocalPath: "images/locations/wildflowers.jpg",
    googleMapsQuery: "flower farm botantical garden"
  },
  {
    id: "sunflowers",
    title: "Late Summer Sunflower Field",
    category: "Nature & Outdoors",
    vibe: "Playful",
    outfit: "Casual",
    props: "Sunflowers",
    gender: "female",
    poseDescription: "Framed waist-up between massive golden sunflower blooms with bright joyful smile.",
    originalLocation: "Sunflower Patch Farm, Middle TN",
    originalCaption: "Sunflowers bloom in late summer—Liza selected a patch 30 mins from studio.",
    imageLocalPath: "images/locations/sunflowers.jpg",
    googleMapsQuery: "sunflower field farm"
  },
  {
    id: "beach_boy",
    title: "Relaxed Beach & Ocean Waves",
    category: "Nature & Outdoors",
    vibe: "Casual",
    outfit: "Casual",
    props: "Ocean",
    gender: "male",
    poseDescription: "Casual hoodie and jeans walk on wet sand near surf shoreline.",
    originalLocation: "Destin Beach Shoreline, FL",
    originalCaption: "Baylor scheduled a fall break beach shoot with relaxed coastal style.",
    imageLocalPath: "images/locations/beach_boy.jpg",
    googleMapsQuery: "public beach shoreline"
  },
  {
    id: "beach_jetties",
    title: "Rock Jetties & Coastline",
    category: "Nature & Outdoors",
    vibe: "Dreamy",
    outfit: "Dress",
    props: "Rock Jetties",
    gender: "female",
    poseDescription: "Seated on sea wall / rock jetty rocks with ocean breeze and coastal sky.",
    originalLocation: "Destin Jetties & Dunes, FL",
    originalCaption: "Reagan loved the unique structural look of beach jetties and emerald water.",
    imageLocalPath: "images/locations/beach_jetties.jpg",
    googleMapsQuery: "coastal jetty beach pier"
  },
  {
    id: "beach_palm_trees",
    title: "Palm Tree Sidewalk Path",
    category: "Nature & Outdoors",
    vibe: "Classic",
    outfit: "Sports",
    props: "Palm Trees",
    gender: "male",
    poseDescription: "Standing under lush palm fronds in university polo and baseball cap.",
    originalLocation: "Sidewalk near Destin Jetties, FL",
    originalCaption: "Briley incorporated palm trees for his FSU college announcement photo.",
    imageLocalPath: "images/locations/beach_palm_trees.jpg",
    googleMapsQuery: "palm tree walkway park"
  },
  {
    id: "gallatin_square_urban",
    title: "Historic Town Square & Brick",
    category: "City & Urban",
    vibe: "Classic",
    outfit: "Casual",
    props: "Architectural Brick",
    gender: "female",
    poseDescription: "Walking across brick alleyway with vintage storefront windows behind.",
    originalLocation: "Historic Gallatin Town Square, Gallatin, TN",
    originalCaption: "Charming downtown area with vintage storefronts, brick walls, and ironwork.",
    imageLocalPath: "images/locations/gallatin_square_urban.jpg",
    googleMapsQuery: "historic downtown town square"
  },
  {
    id: "urban_door_wall",
    title: "Weathered Urban Alley Door",
    category: "City & Urban",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Painted Door",
    gender: "female",
    poseDescription: "Leaning shoulder against teal/grey painted industrial alley door in bold contrast outfit.",
    originalLocation: "Downtown Alley, Middle TN",
    originalCaption: "Abigail's vibrant outfit popping against rustic urban brick & doorway textures.",
    imageLocalPath: "images/locations/urban_door_wall.jpg",
    googleMapsQuery: "downtown brick alleyway"
  },
  {
    id: "flower_truck",
    title: "Mobile Vintage Flower Truck",
    category: "City & Urban",
    vibe: "Dreamy",
    outfit: "Dress",
    props: "Flowers",
    gender: "female",
    poseDescription: "Leaning near bed of flower pop-up truck holding fresh bouquet in lace dress.",
    originalLocation: "Amelia's Flower Truck Pop-Up, 12 South, Nashville",
    originalCaption: "Lace dress paired with Amelia's Flower Truck for a dreamy, girly aesthetic.",
    imageLocalPath: "images/locations/flower_truck.jpg",
    googleMapsQuery: "flower truck pop up garden market"
  },
  {
    id: "12south_ivy_wall",
    title: "Stucco Wall & Green Ivy",
    category: "City & Urban",
    vibe: "Classic",
    outfit: "Dress",
    props: "Ivy Greenery",
    gender: "female",
    poseDescription: "Full-length posture leaning against warm stucco wall draped in climbing ivy.",
    originalLocation: "12 South Boutique Side Streets, Nashville, TN",
    originalCaption: "Claire wandering quiet side streets in 12 South for peaceful urban spots.",
    imageLocalPath: "images/locations/12south_ivy_wall.jpg",
    googleMapsQuery: "ivy covered wall courtyard"
  },
  {
    id: "12south_metal_stairs",
    title: "Industrial Metal Fire Escape",
    category: "City & Urban",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Metal Staircase",
    gender: "female",
    poseDescription: "Seated on metal stair step looking down toward camera with leading line geometry.",
    originalLocation: "12 South Alley Staircase, Nashville, TN",
    originalCaption: "Quiet spot off 12 South side street giving architectural metal lines.",
    imageLocalPath: "images/locations/12south_metal_stairs.jpg",
    googleMapsQuery: "fire escape staircase alley"
  },
  {
    id: "gulch_urban_city",
    title: "Trendy City Street & Boutiques",
    category: "City & Urban",
    vibe: "Classic",
    outfit: "Casual",
    props: "Modern Storefront",
    gender: "female",
    poseDescription: "Candid walking stride along clean modern city sidewalk with blurred background buildings.",
    originalLocation: "The Gulch Neighborhood, Nashville, TN",
    originalCaption: "Walkable urban neighborhood giving photos an elevated city vibe.",
    imageLocalPath: "images/locations/gulch_urban_city.jpg",
    googleMapsQuery: "downtown boutique shopping street"
  },
  {
    id: "printers_alley",
    title: "Neon Alley & Twinkle Lights",
    category: "City & Urban",
    vibe: "Moody",
    outfit: "Formal",
    props: "String Lights",
    gender: "female",
    poseDescription: "Spontaneous laugh/turn in cobblestone alley lit by overhead string bulbs and neon signs.",
    originalLocation: "Printer's Alley, Downtown Nashville, TN",
    originalCaption: "Bailey in Printer's Alley with brick walls, glowing signs, and playful energy.",
    imageLocalPath: "images/locations/printers_alley.jpg",
    googleMapsQuery: "historic alley string lights"
  },
  {
    id: "mural_alley",
    title: "Painted Art Alley & Lighting",
    category: "City & Urban",
    vibe: "Moody",
    outfit: "Casual",
    props: "Wall Art",
    gender: "female",
    poseDescription: "Three-quarter pose in narrow alley with wall shadows and directional side light.",
    originalLocation: "Downtown Mural Alleyway, Nashville, TN",
    originalCaption: "Moody lighting and colorful wall murals added artistic flair to Claire's shoot.",
    imageLocalPath: "images/locations/mural_alley.jpg",
    googleMapsQuery: "mural alley art district"
  },
  {
    id: "graffiti_wall",
    title: "Bold Vibrant Graffiti Wall",
    category: "City & Urban",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Graffiti",
    gender: "female",
    poseDescription: "Crossed-arms confidence stance centered against bright saturated graffiti aerosol graphics.",
    originalLocation: "Gulch Graffiti Wall, Nashville, TN",
    originalCaption: "Sarah loved the eye-catching pops of bright color on this Gulch spray art wall.",
    imageLocalPath: "images/locations/graffiti_wall.jpg",
    googleMapsQuery: "graffiti mural wall street art"
  },
  {
    id: "rooftop_parking",
    title: "Downtown Skyline Rooftop",
    category: "Skyline & Views",
    vibe: "Dreamy",
    outfit: "Casual",
    props: "Skyline View",
    gender: "female",
    poseDescription: "Sitting on perimeter ledge with open sky and city high-rises softly blurred behind.",
    originalLocation: "Downtown Parking Garage Rooftop, Nashville, TN",
    originalCaption: "Rooftop parking garages offer clean lines, minimalist backdrops, and golden hour sunsets.",
    imageLocalPath: "images/locations/rooftop_parking.jpg",
    googleMapsQuery: "downtown parking garage rooftop view"
  },
  {
    id: "pedestrian_bridge",
    title: "Steel Truss Pedestrian Bridge",
    category: "Skyline & Views",
    vibe: "Moody",
    outfit: "Dress",
    props: "Bridge Trusses",
    gender: "female",
    poseDescription: "Standing center between repeating steel arches at sunset looking back into camera.",
    originalLocation: "John Seigenthaler Pedestrian Bridge, Nashville, TN",
    originalCaption: "Pedestrian Bridge captures skyline reflections and sunset hues over the river.",
    imageLocalPath: "images/locations/pedestrian_bridge.jpg",
    googleMapsQuery: "pedestrian bridge river view"
  },
  {
    id: "capitol_building",
    title: "State Capitol Stone Columns",
    category: "Skyline & Views",
    vibe: "Classic",
    outfit: "Suit",
    props: "Gavel / Portfolio",
    gender: "female",
    poseDescription: "Professional stance between grand limestone pillars in tailored skirt suit holding gavel.",
    originalLocation: "Tennessee State Capitol, Nashville, TN",
    originalCaption: "Ella chose the Capitol building reflecting her SGA leadership and legal career goal.",
    imageLocalPath: "images/locations/capitol_building.jpg",
    googleMapsQuery: "state capitol government building columns"
  },
  {
    id: "rocky_construction",
    title: "Raw Rock Quarry & Gold Sequins",
    category: "Industrial & Textures",
    vibe: "Edgy",
    outfit: "Dress",
    props: "Rock Texture",
    gender: "female",
    poseDescription: "High-contrast dramatic pose sitting on angular rock mound wearing metallic sequin gown.",
    originalLocation: "Industrial Quarry Lot, Hendersonville, TN",
    originalCaption: "High contrast of Abigail's gold sequined gown against raw crushed stone backdrop.",
    imageLocalPath: "images/locations/rocky_construction.jpg",
    googleMapsQuery: "quarry gravel lot industrial site"
  },
  {
    id: "chain_link_fence_girl",
    title: "Industrial Chain Link Fence",
    category: "Industrial & Textures",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Wire Fence",
    gender: "female",
    poseDescription: "Hands woven lightly into chain-link fence wire with glowing backlight bokeh.",
    originalLocation: "Commercial Lot Fence, Hendersonville, TN",
    originalCaption: "Rachel posing by unexpected chain link fence with warm sunset light behind.",
    imageLocalPath: "images/locations/chain_link_fence_girl.jpg",
    googleMapsQuery: "industrial fence commercial lot"
  },
  {
    id: "chain_link_fence_colorful",
    title: "Pop-Color Outfit & Wire Grid",
    category: "Industrial & Textures",
    vibe: "Playful",
    outfit: "Casual",
    props: "Wire Grid",
    gender: "female",
    poseDescription: "Horizontal framing leaning arms over top fence bar in bright casual sweater.",
    originalLocation: "Secondary Lot Fence, Middle TN",
    originalCaption: "Abigail's bright outfit adding a pop of fun color to industrial fencing.",
    imageLocalPath: "images/locations/chain_link_fence_colorful.jpg",
    googleMapsQuery: "chain link fence urban grid"
  },
  {
    id: "metal_garage_door",
    title: "Rust Orange Industrial Garage",
    category: "Industrial & Textures",
    vibe: "Edgy",
    outfit: "Casual",
    props: "Corrugated Metal",
    gender: "male",
    poseDescription: "Leaning back against ribbed rust-orange painted metal door with hands in pockets.",
    originalLocation: "Abandoned Car Wash, Hendersonville, TN",
    originalCaption: "Gavin at an abandoned car wash with rust orange garage door texture.",
    imageLocalPath: "images/locations/metal_garage_door.jpg",
    googleMapsQuery: "abandoned garage corrugated metal door"
  },
  {
    id: "high_school_bleachers",
    title: "High School Stadium Bleachers",
    category: "High School Campus",
    vibe: "Classic",
    outfit: "Sports",
    props: "Sports Gear",
    gender: "male",
    poseDescription: "Seated on aluminum bleacher bench with sports stick and team jacket.",
    originalLocation: "Pope John Paul II High School, Hendersonville, TN",
    originalCaption: "Hayden incorporated lacrosse gear on high school stadium bleachers.",
    imageLocalPath: "images/locations/high_school_bleachers.jpg",
    googleMapsQuery: "high school stadium bleachers"
  },
  {
    id: "high_school_track",
    title: "Running Track Red Lanes",
    category: "High School Campus",
    vibe: "Classic",
    outfit: "Sports",
    props: "Track Oval",
    gender: "male",
    poseDescription: "Runner crouch start stance on lane white line of red rubber track surface.",
    originalLocation: "High School Track Oval, Middle TN",
    originalCaption: "Gavin celebrating track scholarship with photos directly on high school track lanes.",
    imageLocalPath: "images/locations/high_school_track.jpg",
    googleMapsQuery: "high school running track field"
  },
  {
    id: "football_field_lacrosse",
    title: "Varsity Field Endzone & Turf",
    category: "High School Campus",
    vibe: "Classic",
    outfit: "Sports",
    props: "Sports Equipment",
    gender: "male",
    poseDescription: "Standing holding helmet/stick on green field turf near goalpost.",
    originalLocation: "Varsity Stadium Field, Hendersonville, TN",
    originalCaption: "Hayden on varsity football field with lacrosse jersey and letter jacket.",
    imageLocalPath: "images/locations/football_field_lacrosse.jpg",
    googleMapsQuery: "high school football athletic field"
  },
  {
    id: "baseball_field",
    title: "Dugout & Baseball Diamond",
    category: "High School Campus",
    vibe: "Classic",
    outfit: "Sports",
    props: "Bat / Glove",
    gender: "male",
    poseDescription: "Seated on dugout bench resting bat over shoulder looking toward home plate.",
    originalLocation: "Beech High School Baseball Field, Shackle Island, TN",
    originalCaption: "Houston including his high school baseball career in his senior portraits.",
    imageLocalPath: "images/locations/baseball_field.jpg",
    googleMapsQuery: "baseball diamond dugout field"
  },
  {
    id: "campus_letter_jacket",
    title: "Campus Courtyard & Letter Jacket",
    category: "High School Campus",
    vibe: "Classic",
    outfit: "Sports",
    props: "Letter Jacket",
    gender: "male",
    poseDescription: "Standing near high school archway wearing varsity letter jacket.",
    originalLocation: "Pope John Paul II Campus Courtyard, Hendersonville, TN",
    originalCaption: "Hayden wearing varsity letter jacket on high school grounds.",
    imageLocalPath: "images/locations/campus_letter_jacket.jpg",
    googleMapsQuery: "high school campus courtyard"
  },
  {
    id: "studio_headshot",
    title: "Clean Studio Headshot & Backdrop",
    category: "Studio",
    vibe: "Classic",
    outfit: "Dress",
    props: "Studio Stool",
    gender: "female",
    poseDescription: "Timeless seated stool headshot on neutral grey backdrop with studio softbox lighting.",
    originalLocation: "Shannon Payne Studio, Hendersonville, TN",
    originalCaption: "Timeless studio headshot ideal for graduation announcements, resumes, and Greek recruitment.",
    imageLocalPath: "images/locations/studio_headshot.jpg",
    googleMapsQuery: "portrait studio headshot rental"
  }
];
